import 'dotenv/config';

import { db, pool } from './client.js';
import { destinations, events, itineraryStops, trips, userPrivateGems, users } from './schema.js';

// Synthetic-only, per CLAUDE.md: nothing here is a real Rochester / Finger
// Lakes business, and none of it should ever be copied into a non-dev
// environment. Every row is tagged `seed: true` in its metadata (where the
// table has a JSONB column) so it can be found and wiped independently of
// real content later.

async function main() {
  const [alice, bob] = await db
    .insert(users)
    .values([
      { email: 'seed-alice@example.test', displayName: 'Seed Alice' },
      { email: 'seed-bob@example.test', displayName: 'Seed Bob' },
    ])
    .returning();

  const [overlook, cidery] = await db
    .insert(destinations)
    .values([
      {
        slug: 'seed-willow-bend-overlook',
        title: 'Willow Bend Overlook (seed)',
        tagline: 'Fictional gorge-side overlook used only for dev/staging seed data.',
        description: 'Placeholder destination generated by server/src/db/seed.ts — not a real place.',
        region: 'GENESEE_VALLEY',
        category: 'NATURE_WATERFALLS',
        latitude: '42.6074000',
        longitude: '-77.6892000',
        coverImageUrl: 'https://example.test/images/willow-bend-overlook.jpg',
        isFlowerCityWaypoint: false,
        metadata: { seed: true },
      },
      {
        slug: 'seed-cobblestone-cidery',
        title: 'Cobblestone Cidery (seed)',
        tagline: 'Fictional cidery used only for dev/staging seed data.',
        description: 'Placeholder destination generated by server/src/db/seed.ts — not a real place.',
        region: 'CANANDAIGUA',
        category: 'WINERY_BREWERY',
        latitude: '42.8709000',
        longitude: '-77.2822000',
        coverImageUrl: 'https://example.test/images/cobblestone-cidery.jpg',
        isFlowerCityWaypoint: true,
        metadata: { seed: true },
      },
    ])
    .returning();

  await db.insert(events).values([
    {
      title: 'Seed Acoustic Set',
      artistName: 'The Placeholder Trio',
      venueDestinationId: cidery.id,
      genre: 'FOLK_ACOUSTIC',
      startTime: new Date('2026-10-01T23:00:00Z'),
      endTime: new Date('2026-10-02T01:00:00Z'),
      description: 'Fictional event generated by server/src/db/seed.ts.',
    },
  ]);

  const [trip] = await db
    .insert(trips)
    .values([{ userId: alice.id, title: 'Seed Weekend Loop', description: 'Fictional trip generated by seed.ts.' }])
    .returning();

  await db.insert(itineraryStops).values([
    { tripId: trip.id, destinationId: overlook.id, stopOrder: 1, dayNumber: 1, durationMinutes: 45 },
    { tripId: trip.id, destinationId: cidery.id, stopOrder: 2, dayNumber: 1, durationMinutes: 60 },
  ]);

  await db.insert(userPrivateGems).values([
    {
      userId: bob.id,
      title: 'Seed Hidden Ledge',
      landmarkNote: 'Behind the fictional red barn used only in seed data.',
      notes: 'Fictional private gem generated by server/src/db/seed.ts — proves landmark_note, audio_url, ideal_season and golden_hour all round-trip.',
      category: 'CIVIC_LANDMARK',
      audioUrl: 'https://example.test/audio/seed-memo.m4a',
      idealSeason: 'SPRING_LILAC',
      goldenHour: 'GOLDEN_HOUR',
      latitude: '42.7000000',
      longitude: '-77.5000000',
    },
  ]);

  console.log('Seed complete: 2 users, 2 destinations, 1 event, 1 trip, 2 stops, 1 private gem.');
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
