// C1: parses the design token sections out of ../../../DESIGN.md's YAML
// frontmatter (colors, typography, rounded, spacing) and renders them as a
// TypeScript module. Shared by generate-tokens.js (writes theme/tokens.ts)
// and check-tokens-generated.js (fails if that file is stale), so the two
// can never drift from each other about what "generated" means.
const fs = require('fs');
const path = require('path');

const DESIGN_MD = path.join(__dirname, '..', '..', '..', 'DESIGN.md');

function stripQuotes(value) {
  const trimmed = value.trim();
  const isSingleQuoted = trimmed.startsWith("'") && trimmed.endsWith("'");
  const isDoubleQuoted = trimmed.startsWith('"') && trimmed.endsWith('"');
  if (isSingleQuoted || isDoubleQuoted) return trimmed.slice(1, -1);
  return trimmed;
}

function indentOf(line) {
  return line.match(/^ */)[0].length;
}

function parseFlatSection(lines, startIndex) {
  const data = {};
  let i = startIndex + 1;
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') continue;
    if (indentOf(line) < 2) break;
    const match = line.match(/^ {2}([\w-]+):\s*(.+)$/);
    if (!match) throw new Error(`design-tokens: unexpected line in flat section: ${JSON.stringify(line)}`);
    data[match[1]] = stripQuotes(match[2]);
  }
  return { data, nextIndex: i };
}

function parseTypographySection(lines, startIndex) {
  const data = {};
  let currentKey = null;
  let i = startIndex + 1;
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') continue;
    const indent = indentOf(line);
    if (indent < 2) break;
    if (indent === 2) {
      const match = line.match(/^ {2}([\w-]+):\s*$/);
      if (!match) throw new Error(`design-tokens: unexpected typography key line: ${JSON.stringify(line)}`);
      currentKey = match[1];
      data[currentKey] = {};
    } else {
      const match = line.match(/^ {4}(\w+):\s*(.+)$/);
      if (!match || !currentKey) {
        throw new Error(`design-tokens: unexpected typography value line: ${JSON.stringify(line)}`);
      }
      data[currentKey][match[1]] = stripQuotes(match[2]);
    }
  }
  return { data, nextIndex: i };
}

const FLAT_SECTIONS = { colors: 'colors', rounded: 'radius', spacing: 'spacing' };

function readDesignTokens(designMdPath = DESIGN_MD) {
  const raw = fs.readFileSync(designMdPath, 'utf8');
  const frontmatterMatch = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!frontmatterMatch) throw new Error(`design-tokens: no YAML frontmatter found in ${designMdPath}`);

  const lines = frontmatterMatch[1].split('\n').map((l) => l.replace(/\r$/, ''));
  const tokens = { colors: {}, typography: {}, radius: {}, spacing: {} };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const sectionMatch = line.match(/^([\w-]+):\s*$/);
    if (!sectionMatch) continue;
    const section = sectionMatch[1];

    if (section === 'typography') {
      const { data, nextIndex } = parseTypographySection(lines, i);
      tokens.typography = data;
      i = nextIndex - 1;
    } else if (FLAT_SECTIONS[section]) {
      const { data, nextIndex } = parseFlatSection(lines, i);
      tokens[FLAT_SECTIONS[section]] = data;
      i = nextIndex - 1;
    }
  }

  return tokens;
}

function emitObject(obj, indent) {
  return Object.entries(obj)
    .map(([key, value]) => {
      if (value && typeof value === 'object') {
        return `${indent}'${key}': {\n${emitObject(value, indent + '  ')}\n${indent}},`;
      }
      return `${indent}'${key}': ${JSON.stringify(value)},`;
    })
    .join('\n');
}

function renderTokensFile(tokens) {
  return `// GENERATED by scripts/generate-tokens.js from ../DESIGN.md's frontmatter.
// Do not hand-edit — change DESIGN.md, then run \`npm run generate:tokens\`.

export const colors = {
${emitObject(tokens.colors, '  ')}
} as const;

export const typography = {
${emitObject(tokens.typography, '  ')}
} as const;

export const radius = {
${emitObject(tokens.radius, '  ')}
} as const;

export const spacing = {
${emitObject(tokens.spacing, '  ')}
} as const;
`;
}

module.exports = { readDesignTokens, renderTokensFile, DESIGN_MD };
